package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auspicio generated by hbm2java
 */
@Entity
@Table(name="auspicio"
    ,catalog="urcipy"
)
public class Auspicio  implements java.io.Serializable {


     private Integer idauspicio;
     private Regional regional;
     private String comentario;
     private String ruta;
     private String titulo;
     private Date fechadesde;
     private Date fechahasta;
     private Integer activo;

    public Auspicio() {
    }

	
    public Auspicio(Regional regional) {
        this.regional = regional;
    }
    public Auspicio(Regional regional, String comentario, String ruta, String titulo, Date fechadesde, Date fechahasta, Integer activo) {
       this.regional = regional;
       this.comentario = comentario;
       this.ruta = ruta;
       this.titulo = titulo;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
       this.activo = activo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idauspicio", unique=true, nullable=false)
    public Integer getIdauspicio() {
        return this.idauspicio;
    }
    
    public void setIdauspicio(Integer idauspicio) {
        this.idauspicio = idauspicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

    
    @Column(name="comentario", length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="ruta", length=45)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="titulo", length=45)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechadesde", length=10)
    public Date getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(Date fechadesde) {
        this.fechadesde = fechadesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechahasta", length=10)
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }

    
    @Column(name="activo")
    public Integer getActivo() {
        return this.activo;
    }
    
    public void setActivo(Integer activo) {
        this.activo = activo;
    }




}


