package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Campeones generated by hbm2java
 */
@Entity
@Table(name="campeones"
    ,catalog="urcipy"
)
public class Campeones  implements java.io.Serializable {


     private Integer idcampeones;
     private Categoriah categoriah;
     private Ciudad ciudad;
     private Club club;
     private Regional regional;
     private String nombre;
     private String apellido;
     private String ci;
     private Integer sexo;
     private Date fecnac;
     private String telefono;
     private String direccion;
     private String email;
     private Integer courci;
     private String nacionalidad;
     private Integer ano;
     private Integer peso;
     private Integer altura;
     private String bici;
     private String velmedia;
     private Integer puntos;
     private Integer puesto;
     private String rutabici;
     private String ruta;
     private String gruposanguineo;
     private Double promedio;
     private Integer kmts;
     private Integer cantidad;

    public Campeones() {
    }

	
    public Campeones(Categoriah categoriah, Ciudad ciudad, Club club, Regional regional) {
        this.categoriah = categoriah;
        this.ciudad = ciudad;
        this.club = club;
        this.regional = regional;
    }
    public Campeones(Categoriah categoriah, Ciudad ciudad, Club club, Regional regional, String nombre, String apellido, String ci, Integer sexo, Date fecnac, String telefono, String direccion, String email, Integer courci, String nacionalidad, Integer ano, Integer peso, Integer altura, String bici, String velmedia, Integer puntos, Integer puesto, String rutabici, String ruta, String gruposanguineo, Double promedio, Integer kmts, Integer cantidad) {
       this.categoriah = categoriah;
       this.ciudad = ciudad;
       this.club = club;
       this.regional = regional;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ci = ci;
       this.sexo = sexo;
       this.fecnac = fecnac;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.courci = courci;
       this.nacionalidad = nacionalidad;
       this.ano = ano;
       this.peso = peso;
       this.altura = altura;
       this.bici = bici;
       this.velmedia = velmedia;
       this.puntos = puntos;
       this.puesto = puesto;
       this.rutabici = rutabici;
       this.ruta = ruta;
       this.gruposanguineo = gruposanguineo;
       this.promedio = promedio;
       this.kmts = kmts;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcampeones", unique=true, nullable=false)
    public Integer getIdcampeones() {
        return this.idcampeones;
    }
    
    public void setIdcampeones(Integer idcampeones) {
        this.idcampeones = idcampeones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoriah", nullable=false)
    public Categoriah getCategoriah() {
        return this.categoriah;
    }
    
    public void setCategoriah(Categoriah categoriah) {
        this.categoriah = categoriah;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idciudad", nullable=false)
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclub", nullable=false)
    public Club getClub() {
        return this.club;
    }
    
    public void setClub(Club club) {
        this.club = club;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="ci", length=20)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="sexo")
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecnac", length=10)
    public Date getFecnac() {
        return this.fecnac;
    }
    
    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }

    
    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="courci")
    public Integer getCourci() {
        return this.courci;
    }
    
    public void setCourci(Integer courci) {
        this.courci = courci;
    }

    
    @Column(name="nacionalidad", length=45)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="ano")
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }

    
    @Column(name="peso")
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }

    
    @Column(name="altura")
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }

    
    @Column(name="bici", length=45)
    public String getBici() {
        return this.bici;
    }
    
    public void setBici(String bici) {
        this.bici = bici;
    }

    
    @Column(name="velmedia", length=45)
    public String getVelmedia() {
        return this.velmedia;
    }
    
    public void setVelmedia(String velmedia) {
        this.velmedia = velmedia;
    }

    
    @Column(name="puntos")
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }

    
    @Column(name="puesto")
    public Integer getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(Integer puesto) {
        this.puesto = puesto;
    }

    
    @Column(name="rutabici", length=45)
    public String getRutabici() {
        return this.rutabici;
    }
    
    public void setRutabici(String rutabici) {
        this.rutabici = rutabici;
    }

    
    @Column(name="ruta", length=45)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="gruposanguineo", length=3)
    public String getGruposanguineo() {
        return this.gruposanguineo;
    }
    
    public void setGruposanguineo(String gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }

    
    @Column(name="promedio", precision=22, scale=0)
    public Double getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(Double promedio) {
        this.promedio = promedio;
    }

    
    @Column(name="kmts")
    public Integer getKmts() {
        return this.kmts;
    }
    
    public void setKmts(Integer kmts) {
        this.kmts = kmts;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


