package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="ciudad"
    ,catalog="urcipy"
)
public class Ciudad  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idciudad", unique=true, nullable=false)
     private Integer idciudad;
    private String nomciudad;
    @ManyToOne(fetch=FetchType.EAGER)
     private Pais pais;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="ciudad")
    @JsonIgnore
     private Set<Corredor> corredors = new HashSet<>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="ciudad")
    @JsonIgnore
     private Set<Campeones> campeoneses = new HashSet<>(0);

    public Ciudad() {
    }

	
    public Ciudad(Pais pais) {
        this.pais = pais;
    }
    public Ciudad(Pais pais, String nomciudad, Set<Corredor> corredors, Set<Campeones> campeoneses) {
       this.pais = pais;
       this.nomciudad = nomciudad;
       this.corredors = corredors;
       this.campeoneses = campeoneses;
    }
   

    public Integer getIdciudad() {
        return this.idciudad;
    }
    
    public void setIdciudad(Integer idciudad) {
        this.idciudad = idciudad;
    }


    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="nomciudad", length=30)
    public String getNomciudad() {
        return this.nomciudad;
    }
    
    public void setNomciudad(String nomciudad) {
        this.nomciudad = nomciudad;
    }


    public Set<Corredor> getCorredors() {
        return this.corredors;
    }
    
    public void setCorredors(Set<Corredor> corredors) {
        this.corredors = corredors;
    }


    public Set<Campeones> getCampeoneses() {
        return this.campeoneses;
    }
    
    public void setCampeoneses(Set<Campeones> campeoneses) {
        this.campeoneses = campeoneses;
    }




}


