package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Club generated by hbm2java
 */
@Entity
@Table(name="club"
    ,catalog="urcipy"
)
public class Club  implements java.io.Serializable {


     private Integer idclub;
     private Regional regional;
     private String nomclub;
     private String presidente;
     private String telpresi;
     private String vicepresidente;
     private String telvice;
     private String telefono;
     private String email;
     private String ruta;
     private String rutagrande;
     private Set<Evento> eventos = new HashSet<Evento>(0);
     private Set<Campeones> campeoneses = new HashSet<Campeones>(0);
     private Set<Corredor> corredors = new HashSet<Corredor>(0);

    private Set<Participante> participantes = new HashSet<>(0);

    public Club() {
    }

	
    public Club(Regional regional) {
        this.regional = regional;
    }
    public Club(Regional regional, String nomclub, String presidente, String telpresi, String vicepresidente, String telvice, String telefono, String email, String ruta, String rutagrande, Set<Evento> eventos, Set<Campeones> campeoneses, Set<Corredor> corredors, Set<Participante> participantes) {
       this.regional = regional;
       this.nomclub = nomclub;
       this.presidente = presidente;
       this.telpresi = telpresi;
       this.vicepresidente = vicepresidente;
       this.telvice = telvice;
       this.telefono = telefono;
       this.email = email;
       this.ruta = ruta;
       this.rutagrande = rutagrande;
       this.eventos = eventos;
       this.campeoneses = campeoneses;
       this.corredors = corredors;
       this.participantes=participantes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclub", unique=true, nullable=false)
    public Integer getIdclub() {
        return this.idclub;
    }
    
    public void setIdclub(Integer idclub) {
        this.idclub = idclub;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="regional_idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

    
    @Column(name="nomclub", length=45)
    public String getNomclub() {
        return this.nomclub;
    }
    
    public void setNomclub(String nomclub) {
        this.nomclub = nomclub;
    }

    
    @Column(name="presidente", length=45)
    public String getPresidente() {
        return this.presidente;
    }
    
    public void setPresidente(String presidente) {
        this.presidente = presidente;
    }

    
    @Column(name="telpresi", length=45)
    public String getTelpresi() {
        return this.telpresi;
    }
    
    public void setTelpresi(String telpresi) {
        this.telpresi = telpresi;
    }

    
    @Column(name="vicepresidente", length=45)
    public String getVicepresidente() {
        return this.vicepresidente;
    }
    
    public void setVicepresidente(String vicepresidente) {
        this.vicepresidente = vicepresidente;
    }

    
    @Column(name="telvice", length=45)
    public String getTelvice() {
        return this.telvice;
    }
    
    public void setTelvice(String telvice) {
        this.telvice = telvice;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ruta", length=45)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="rutagrande", length=45)
    public String getRutagrande() {
        return this.rutagrande;
    }
    
    public void setRutagrande(String rutagrande) {
        this.rutagrande = rutagrande;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="club")
@JsonIgnore
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="club")
@JsonIgnore
    public Set<Campeones> getCampeoneses() {
        return this.campeoneses;
    }
    
    public void setCampeoneses(Set<Campeones> campeoneses) {
        this.campeoneses = campeoneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="club")
@JsonIgnore
    public Set<Corredor> getCorredors() {
        return this.corredors;
    }
    
    public void setCorredors(Set<Corredor> corredors) {
        this.corredors = corredors;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="club")
    @JsonIgnore
    public Set<Participante> getParticipantes() {
        return this.participantes;
    }

    public void setParticipantes(Set<Participante> participantes) {
        this.participantes = participantes;
    }



}


