package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Concepto generated by hbm2java
 */
@Entity
@Table(name="concepto"
    ,catalog="urcipy"
)
public class Concepto  implements java.io.Serializable {


     private int idconcepto;
     private Regional regional;
     private String nomconcepto;
     private Byte tipo;
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

    public Concepto() {
    }

	
    public Concepto(int idconcepto, Regional regional) {
        this.idconcepto = idconcepto;
        this.regional = regional;
    }
    public Concepto(int idconcepto, Regional regional, String nomconcepto, Byte tipo, Set<Movimiento> movimientos) {
       this.idconcepto = idconcepto;
       this.regional = regional;
       this.nomconcepto = nomconcepto;
       this.tipo = tipo;
       this.movimientos = movimientos;
    }
   
     @Id 

    
    @Column(name="idconcepto", unique=true, nullable=false)
    public int getIdconcepto() {
        return this.idconcepto;
    }
    
    public void setIdconcepto(int idconcepto) {
        this.idconcepto = idconcepto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="regional_idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

    
    @Column(name="nomconcepto", length=60)
    public String getNomconcepto() {
        return this.nomconcepto;
    }
    
    public void setNomconcepto(String nomconcepto) {
        this.nomconcepto = nomconcepto;
    }

    
    @Column(name="tipo")
    public Byte getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Byte tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="concepto")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }




}


