package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Yo generated by yo
 */
@Entity
@Table(name="corredor_club_regional"
    ,catalog="urcipy"
)
public class CorredorClubRegional implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    private Integer idcorredorClubRegional;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="corredor_idcorredor", nullable=false)
    private Corredor corredor;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="club_idclub", nullable=false)
     private Club club;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="regional_idregional", nullable=false)
     private Regional regional;
   /* private Integer montoranking; para realizar en una nueva entidad
    private Integer puntua;*/

    public CorredorClubRegional() {

    }

    public CorredorClubRegional(Corredor corredor, Club club, Regional regional) {
        this.corredor = corredor;
        this.club = club;
        this.regional = regional;

    }

    public Integer getIdcorredorClubRegional() {
        return idcorredorClubRegional;
    }

    public void setIdcorredorClubRegional(Integer idcorredorClubRegional) {
        this.idcorredorClubRegional = idcorredorClubRegional;
    }

    public Corredor getCorredor() {
        return corredor;
    }

    public void setCorredor(Corredor corredor) {
        this.corredor = corredor;
    }

    public Club getClub() {
        return club;
    }

    public void setClub(Club club) {
        this.club = club;
    }

    public Regional getRegional() {
        return regional;
    }

    public void setRegional(Regional regional) {
        this.regional = regional;
    }


}


