package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Corredor generated by hbm2java
 */
@Entity
@Table(name="corredor"
    ,catalog="urcipy"
)
public class Corredor  implements java.io.Serializable {


     private Integer idcorredor;
     private Categoria categoria;
     private Ciudad ciudad;
     private Club club;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String ci;
     private Integer sexo;
     private Date fecnac;
     private String telefono;
     private String direccion;
     private String email;
     private Integer courci;
     private String nacionalidad;
     private String carnet;
     private String cidelante;
     private String ciatras;
     private String certificado;
     private String deposito;
     private String docfirma1;
     private String docfirma2;
     private Integer tipocat;
     private String tutorp;
     private String tutorm;
     private String citp;
     private String citm;
     private String domicilio;
     private String nrocasa;
     private String ciudadt;
     private String paist;
     private Integer licencia;
     private Integer modificar;
     private String gruposanguineo;
     private Integer puntua;
     private Date fecmodi;
     private Integer montopuntua;
     private Byte carnetfpc;
     private Set imcs = new HashSet<>(0);
     private Set<Participante> participantes = new HashSet<>(0);
     private Set miembroses = new HashSet<>(0);

    public Corredor() {
    }

	
    public Corredor(Categoria categoria, Ciudad ciudad, Club club, Usuario usuario) {
        this.categoria = categoria;
        this.ciudad = ciudad;
        this.club = club;
        this.usuario = usuario;
    }
    public Corredor(Categoria categoria, Ciudad ciudad, Club club, Usuario usuario, String nombre, String apellido, String ci, Integer sexo, Date fecnac, String telefono, String direccion, String email, Integer courci, String nacionalidad, String carnet, String cidelante, String ciatras, String certificado, String deposito, String docfirma1, String docfirma2, Integer tipocat, String tutorp, String tutorm, String citp, String citm, String domicilio, String nrocasa, String ciudadt, String paist, Integer licencia, Integer modificar, String gruposanguineo, Integer puntua, Date fecmodi, Integer montopuntua, Byte carnetfpc, Set imcs, Set<Participante> participantes, Set miembroses) {
       this.categoria = categoria;
       this.ciudad = ciudad;
       this.club = club;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ci = ci;
       this.sexo = sexo;
       this.fecnac = fecnac;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.courci = courci;
       this.nacionalidad = nacionalidad;
       this.carnet = carnet;
       this.cidelante = cidelante;
       this.ciatras = ciatras;
       this.certificado = certificado;
       this.deposito = deposito;
       this.docfirma1 = docfirma1;
       this.docfirma2 = docfirma2;
       this.tipocat = tipocat;
       this.tutorp = tutorp;
       this.tutorm = tutorm;
       this.citp = citp;
       this.citm = citm;
       this.domicilio = domicilio;
       this.nrocasa = nrocasa;
       this.ciudadt = ciudadt;
       this.paist = paist;
       this.licencia = licencia;
       this.modificar = modificar;
       this.gruposanguineo = gruposanguineo;
       this.puntua = puntua;
       this.fecmodi = fecmodi;
       this.montopuntua = montopuntua;
       this.carnetfpc = carnetfpc;
       this.imcs = imcs;
       this.participantes = participantes;
       this.miembroses = miembroses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcorredor", unique=true, nullable=false)
    public Integer getIdcorredor() {
        return this.idcorredor;
    }
    
    public void setIdcorredor(Integer idcorredor) {
        this.idcorredor = idcorredor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idciudad", nullable=false)
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclub", nullable=false)
    public Club getClub() {
        return this.club;
    }
    
    public void setClub(Club club) {
        this.club = club;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="ci", length=20)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="sexo")
    public Integer getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Integer sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecnac", length=10)
    public Date getFecnac() {
        return this.fecnac;
    }
    
    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }

    
    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="courci")
    public Integer getCourci() {
        return this.courci;
    }
    
    public void setCourci(Integer courci) {
        this.courci = courci;
    }

    
    @Column(name="nacionalidad", length=45)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="carnet", length=45)
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }

    
    @Column(name="cidelante", length=45)
    public String getCidelante() {
        return this.cidelante;
    }
    
    public void setCidelante(String cidelante) {
        this.cidelante = cidelante;
    }

    
    @Column(name="ciatras", length=45)
    public String getCiatras() {
        return this.ciatras;
    }
    
    public void setCiatras(String ciatras) {
        this.ciatras = ciatras;
    }

    
    @Column(name="certificado", length=100)
    public String getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }

    
    @Column(name="deposito", length=45)
    public String getDeposito() {
        return this.deposito;
    }
    
    public void setDeposito(String deposito) {
        this.deposito = deposito;
    }

    
    @Column(name="docfirma1", length=45)
    public String getDocfirma1() {
        return this.docfirma1;
    }
    
    public void setDocfirma1(String docfirma1) {
        this.docfirma1 = docfirma1;
    }

    
    @Column(name="docfirma2", length=45)
    public String getDocfirma2() {
        return this.docfirma2;
    }
    
    public void setDocfirma2(String docfirma2) {
        this.docfirma2 = docfirma2;
    }

    
    @Column(name="tipocat")
    public Integer getTipocat() {
        return this.tipocat;
    }
    
    public void setTipocat(Integer tipocat) {
        this.tipocat = tipocat;
    }

    
    @Column(name="tutorp", length=45)
    public String getTutorp() {
        return this.tutorp;
    }
    
    public void setTutorp(String tutorp) {
        this.tutorp = tutorp;
    }

    
    @Column(name="tutorm", length=45)
    public String getTutorm() {
        return this.tutorm;
    }
    
    public void setTutorm(String tutorm) {
        this.tutorm = tutorm;
    }

    
    @Column(name="citp", length=15)
    public String getCitp() {
        return this.citp;
    }
    
    public void setCitp(String citp) {
        this.citp = citp;
    }

    
    @Column(name="citm", length=15)
    public String getCitm() {
        return this.citm;
    }
    
    public void setCitm(String citm) {
        this.citm = citm;
    }

    
    @Column(name="domicilio", length=45)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }

    
    @Column(name="nrocasa", length=5)
    public String getNrocasa() {
        return this.nrocasa;
    }
    
    public void setNrocasa(String nrocasa) {
        this.nrocasa = nrocasa;
    }

    
    @Column(name="ciudadt", length=25)
    public String getCiudadt() {
        return this.ciudadt;
    }
    
    public void setCiudadt(String ciudadt) {
        this.ciudadt = ciudadt;
    }

    
    @Column(name="paist", length=25)
    public String getPaist() {
        return this.paist;
    }
    
    public void setPaist(String paist) {
        this.paist = paist;
    }

    
    @Column(name="licencia")
    public Integer getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Integer licencia) {
        this.licencia = licencia;
    }

    
    @Column(name="modificar")
    public Integer getModificar() {
        return this.modificar;
    }
    
    public void setModificar(Integer modificar) {
        this.modificar = modificar;
    }

    
    @Column(name="gruposanguineo", length=10)
    public String getGruposanguineo() {
        return this.gruposanguineo;
    }
    
    public void setGruposanguineo(String gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }

    
    @Column(name="puntua")
    public Integer getPuntua() {
        return this.puntua;
    }
    
    public void setPuntua(Integer puntua) {
        this.puntua = puntua;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecmodi", length=19)
    public Date getFecmodi() {
        return this.fecmodi;
    }
    
    public void setFecmodi(Date fecmodi) {
        this.fecmodi = fecmodi;
    }

    
    @Column(name="montopuntua")
    public Integer getMontopuntua() {
        return this.montopuntua;
    }
    
    public void setMontopuntua(Integer montopuntua) {
        this.montopuntua = montopuntua;
    }

    
    @Column(name="carnetfpc")
    public Byte getCarnetfpc() {
        return this.carnetfpc;
    }
    
    public void setCarnetfpc(Byte carnetfpc) {
        this.carnetfpc = carnetfpc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    public Set<Imc> getImcs() {
        return this.imcs;
    }
    
    public void setImcs(Set<Imc> imcs) {
        this.imcs = imcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    public Set<Participante> getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set<Participante> participantes) {
        this.participantes = participantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    public Set<Miembros> getMiembroses() {
        return this.miembroses;
    }
    
    public void setMiembroses(Set<Miembros> miembroses) {
        this.miembroses = miembroses;
    }




}


