package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Corredor generated by hbm2java
 */
@Entity
@Table(name="corredor"
    ,catalog="urcipy"
)
public class Corredor  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="idcorredor", unique=true, nullable=false)
     private Integer idcorredor;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="categoria_idcategoria", nullable=false)
     private Categoria categoria;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ciudad_idciudad", nullable=false)
     private Ciudad ciudad;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="club_idclub", nullable=false)
     private Club club;
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="usuario_idusuario", nullable=false)
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String ci;
     private Byte sexo;
     private Date fecnac;
     private String telefono;
     private String direccion;
     private String email;
     private Byte verificar;
     private String nacionalidad;
     private String carnet;
    private String carnetatras;
    private String foto;
     private String cidelante;
     private Byte tipocat;
     private String tutorp;

     private String citp;
     private Integer licencia;
     private Boolean modificar;
     private String gruposanguineo;
     private Integer puntua;
     private Date fecmodi;
     private Integer montopuntua;
     private Byte carnetfpc;
    private String observacion;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    @JsonIgnore
     private Set<Imc> imcs = new HashSet<Imc>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    @JsonIgnore
     private Set<Participante> participantes = new HashSet<Participante>(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="corredor")
    @JsonIgnore
     private Set<Miembros> miembroses = new HashSet<Miembros>(0);

    public Corredor() {
    }


    public Corredor(Categoria categoria, Ciudad ciudad, Club club, Usuario usuario) {
        this.categoria = categoria;
        this.ciudad = ciudad;
        this.club = club;
        this.usuario = usuario;
    }

    public Corredor(Integer idcorredor, Categoria categoria, Ciudad ciudad, Club club, Usuario usuario, String nombre, String apellido, String ci, Byte sexo, Date fecnac, String telefono, String direccion, String email, Byte verificar, String nacionalidad, String carnet, String carnetatras, String foto, String cidelante, Byte tipocat, String tutorp, String citp, Integer licencia, Boolean modificar, String gruposanguineo, Integer puntua, Date fecmodi, Integer montopuntua, Byte carnetfpc, String observacion, Set<Imc> imcs, Set<Participante> participantes, Set<Miembros> miembroses) {
        this.idcorredor = idcorredor;
        this.categoria = categoria;
        this.ciudad = ciudad;
        this.club = club;
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.ci = ci;
        this.sexo = sexo;
        this.fecnac = fecnac;
        this.telefono = telefono;
        this.direccion = direccion;
        this.email = email;
        this.verificar = verificar;
        this.nacionalidad = nacionalidad;
        this.carnet = carnet;
        this.carnetatras = carnetatras;
        this.foto = foto;
        this.cidelante = cidelante;
        this.tipocat = tipocat;
        this.tutorp = tutorp;
        this.citp = citp;
        this.licencia = licencia;
        this.modificar = modificar;
        this.gruposanguineo = gruposanguineo;
        this.puntua = puntua;
        this.fecmodi = fecmodi;
        this.montopuntua = montopuntua;
        this.carnetfpc = carnetfpc;
        this.observacion = observacion;
        this.imcs = imcs;
        this.participantes = participantes;
        this.miembroses = miembroses;
    }


    public Integer getIdcorredor() {
        return this.idcorredor;
    }

    public void setIdcorredor(Integer idcorredor) {
        this.idcorredor = idcorredor;
    }


    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }


    public Ciudad getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    public Club getClub() {
        return this.club;
    }

    public void setClub(Club club) {
        this.club = club;
    }


    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }


    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }


    @Column(name="ci", length=20)
    public String getCi() {
        return this.ci;
    }

    public void setCi(String ci) {
        this.ci = ci;
    }


    @Column(name="sexo")
    public Byte getSexo() {
        return this.sexo;
    }

    public void setSexo(Byte sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecnac", length=10)
    public Date getFecnac() {
        return this.fecnac;
    }

    public void setFecnac(Date fecnac) {
        this.fecnac = fecnac;
    }


    @Column(name="telefono", length=30)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }


    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }


    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    @Column(name="verificar")
    public Byte getVerificar() {
        return verificar;
    }

    public void setVerificar(Byte verificar) {
        this.verificar = verificar;
    }

    @Column(name="nacionalidad", length=45)
    public String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }


    @Column(name="carnet", length=45)
    public String getCarnet() {
        return this.carnet;
    }

    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    @Column(name="carnetatras", length=45)
    public String getCarnetatras() {
        return carnetatras;
    }

    public void setCarnetatras(String carnetatras) {
        this.carnetatras = carnetatras;
    }
    @Column(name="foto", length=45)
    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    @Column(name="cidelante", length=45)
    public String getCidelante() {
        return this.cidelante;
    }

    public void setCidelante(String cidelante) {
        this.cidelante = cidelante;
    }






    @Column(name="tipocat")
    public Byte getTipocat() {
        return this.tipocat;
    }

    public void setTipocat(Byte tipocat) {
        this.tipocat = tipocat;
    }


    @Column(name="tutorp", length=45)
    public String getTutorp() {
        return this.tutorp;
    }

    public void setTutorp(String tutorp) {
        this.tutorp = tutorp;
    }



    @Column(name="citp", length=15)
    public String getCitp() {
        return this.citp;
    }

    public void setCitp(String citp) {
        this.citp = citp;
    }




    @Column(name="licencia")
    public Integer getLicencia() {
        return this.licencia;
    }

    public void setLicencia(Integer licencia) {
        this.licencia = licencia;
    }


    @Column(name="modificar")
    public Boolean getModificar() {
        return this.modificar;
    }

    public void setModificar(Boolean modificar) {
        this.modificar = modificar;
    }


    @Column(name="gruposanguineo", length=10)
    public String getGruposanguineo() {
        return this.gruposanguineo;
    }

    public void setGruposanguineo(String gruposanguineo) {
        this.gruposanguineo = gruposanguineo;
    }


    @Column(name="puntua")
    public Integer getPuntua() {
        return this.puntua;
    }

    public void setPuntua(Integer puntua) {
        this.puntua = puntua;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecmodi", length=19)
    public Date getFecmodi() {
        return this.fecmodi;
    }

    public void setFecmodi(Date fecmodi) {
        this.fecmodi = fecmodi;
    }


    @Column(name="montopuntua")
    public Integer getMontopuntua() {
        return this.montopuntua;
    }

    public void setMontopuntua(Integer montopuntua) {
        this.montopuntua = montopuntua;
    }


    @Column(name="carnetfpc")
    public Byte getCarnetfpc() {
        return this.carnetfpc;
    }

    public void setCarnetfpc(Byte carnetfpc) {
        this.carnetfpc = carnetfpc;
    }
    @Column(name="observacion", length=100)
    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }





    public Set<Imc> getImcs() {
        return this.imcs;
    }
    
    public void setImcs(Set<Imc> imcs) {
        this.imcs = imcs;
    }


    public Set<Participante> getParticipantes() {
        return this.participantes;
    }
    
    public void setParticipantes(Set<Participante> participantes) {
        this.participantes = participantes;
    }


    public Set<Miembros> getMiembroses() {
        return this.miembroses;
    }
    
    public void setMiembroses(Set<Miembros> miembroses) {
        this.miembroses = miembroses;
    }




}


