package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="urcipy"
)
public class Departamento  implements java.io.Serializable {


     private int iddepartamento;
     private String nomdepartamento;
     private Set<Movimiento> movimientos = new HashSet<>(0);

    public Departamento() {
    }

	
    public Departamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public Departamento(int iddepartamento, String nomdepartamento, Set<Movimiento> movimientos) {
       this.iddepartamento = iddepartamento;
       this.nomdepartamento = nomdepartamento;
       this.movimientos = movimientos;
    }
   
     @Id 

    
    @Column(name="iddepartamento", unique=true, nullable=false)
    public int getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(int iddepartamento) {
        this.iddepartamento = iddepartamento;
    }

    
    @Column(name="nomdepartamento", length=45)
    public String getNomdepartamento() {
        return this.nomdepartamento;
    }
    
    public void setNomdepartamento(String nomdepartamento) {
        this.nomdepartamento = nomdepartamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }




}


