package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import java.math.BigDecimal;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Entidad generated by hbm2java
 */
@Entity
@Table(name="historial"
    ,catalog="urcipy"
)
public class Historial implements java.io.Serializable {



    private Integer idparticipante;
    private Date fecha;
     private String nomevento;
     private String ci;
     private String nomparticipante;
     private String club;
     private String categoria;
     private Integer puestocat;
     private BigDecimal promedio;

    public Historial() {
    }

    public Historial(Integer idparticipante, Date fecha, String nomevento, String ci, String nomparticipante, String club, String categoria, Integer puestocat, BigDecimal promedio) {
        this.idparticipante = idparticipante;
        this.fecha = fecha;
        this.nomevento = nomevento;
        this.ci = ci;
        this.nomparticipante = nomparticipante;
        this.club = club;
        this.categoria = categoria;
        this.puestocat = puestocat;
        this.promedio = promedio;
    }
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idparticipante", unique=true, nullable=false)
    public Integer getIdparticipante() {
        return idparticipante;
    }

    public void setIdparticipante(Integer idparticipante) {
        this.idparticipante = idparticipante;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Column(name="nomevento", length=45)
    public String getNomevento() {
        return nomevento;
    }

    public void setNomevento(String nomevento) {
        this.nomevento = nomevento;
    }

    @Column(name="ci", length=20)
    public String getCi() {
        return ci;
    }

    public void setCi(String ci) {
        this.ci = ci;
    }
    @Column(name="nomparticipante", length=90)
    public String getNomparticipante() {
        return nomparticipante;
    }

    public void setNomparticipante(String nomparticipante) {
        this.nomparticipante = nomparticipante;
    }
    @Column(name="club", length=60)
    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }
    @Column(name="categoria", length=60)
    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    @Column(name="puestocat")
    public Integer getPuestocat() {
        return puestocat;
    }

    public void setPuestocat(Integer puestocat) {
        this.puestocat = puestocat;
    }
    @Column(name="promedio")
    public BigDecimal getPromedio() {
        return promedio;
    }

    public void setPromedio(BigDecimal promedio) {
        this.promedio = promedio;
    }


}


