package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Imc generated by hbm2java
 */
@Entity
@Table(name="imc"
    ,catalog="urcipy"
)
public class Imc  implements java.io.Serializable {


     private Integer idimc;
     private Corredor corredor;
     private Date fecha;
     private String nomimc;
     private Byte peso;
     private int idpersonal;

    public Imc() {
    }

	
    public Imc(Corredor corredor, int idpersonal) {
        this.corredor = corredor;
        this.idpersonal = idpersonal;
    }
    public Imc(Corredor corredor, Date fecha, String nomimc, Byte peso, int idpersonal) {
       this.corredor = corredor;
       this.fecha = fecha;
       this.nomimc = nomimc;
       this.peso = peso;
       this.idpersonal = idpersonal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idimc", unique=true, nullable=false)
    public Integer getIdimc() {
        return this.idimc;
    }
    
    public void setIdimc(Integer idimc) {
        this.idimc = idimc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcorredor", nullable=false)
    public Corredor getCorredor() {
        return this.corredor;
    }
    
    public void setCorredor(Corredor corredor) {
        this.corredor = corredor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="nomimc", length=10)
    public String getNomimc() {
        return this.nomimc;
    }
    
    public void setNomimc(String nomimc) {
        this.nomimc = nomimc;
    }

    
    @Column(name="peso")
    public Byte getPeso() {
        return this.peso;
    }
    
    public void setPeso(Byte peso) {
        this.peso = peso;
    }

    
    @Column(name="idpersonal", nullable=false)
    public int getIdpersonal() {
        return this.idpersonal;
    }
    
    public void setIdpersonal(int idpersonal) {
        this.idpersonal = idpersonal;
    }




}


