package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Imc generated by hbm2java
 */
@Entity
@Table(name="imc"
    ,catalog="urcipy"
)
public class Imc  {


     private Integer idimc;
     private Corredor corredor;
     private String nomimc;
     private Date fecha;
     private Byte peso;
     private Integer altura;
     private BigDecimal imc;

    public Imc() {
    }

	
    public Imc(Corredor corredor) {
        this.corredor = corredor;
    }
    public Imc(Corredor corredor, String nomimc, Date fecha, Byte peso, Integer altura, BigDecimal imc) {
       this.corredor = corredor;
       this.nomimc = nomimc;
       this.fecha = fecha;
       this.peso = peso;
       this.altura = altura;
       this.imc = imc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idimc", unique=true, nullable=false)
    public Integer getIdimc() {
        return this.idimc;
    }
    
    public void setIdimc(Integer idimc) {
        this.idimc = idimc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="corredor_idcorredor", nullable=false)
    public Corredor getCorredor() {
        return this.corredor;
    }
    
    public void setCorredor(Corredor corredor) {
        this.corredor = corredor;
    }

    
    @Column(name="nomimc", length=10)
    public String getNomimc() {
        return this.nomimc;
    }
    
    public void setNomimc(String nomimc) {
        this.nomimc = nomimc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="peso")
    public Byte getPeso() {
        return this.peso;
    }
    
    public void setPeso(Byte peso) {
        this.peso = peso;
    }

    
    @Column(name="altura")
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }

    
    @Column(name="imc", precision=3, scale=1)
    public BigDecimal getImc() {
        return this.imc;
    }
    
    public void setImc(BigDecimal imc) {
        this.imc = imc;
    }




}


