package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Miembros generated by hbm2java
 */
@Entity
@Table(name="miembros"
    ,catalog="urcipy"
)
public class Miembros  implements java.io.Serializable {


     private Integer idmiembros;
     private Cargo cargo;
     private Corredor corredor;
     private Byte orden;

    public Miembros() {
    }

	
    public Miembros(Cargo cargo, Corredor corredor) {
        this.cargo = cargo;
        this.corredor = corredor;
    }
    public Miembros(Cargo cargo, Corredor corredor, Byte orden) {
       this.cargo = cargo;
       this.corredor = corredor;
       this.orden = orden;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmiembros", unique=true, nullable=false)
    public Integer getIdmiembros() {
        return this.idmiembros;
    }
    
    public void setIdmiembros(Integer idmiembros) {
        this.idmiembros = idmiembros;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcargo", nullable=false)
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcorredor", nullable=false)
    public Corredor getCorredor() {
        return this.corredor;
    }
    
    public void setCorredor(Corredor corredor) {
        this.corredor = corredor;
    }

    
    @Column(name="orden")
    public Byte getOrden() {
        return this.orden;
    }
    
    public void setOrden(Byte orden) {
        this.orden = orden;
    }




}


