package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name="movimiento"
    ,catalog="urcipy"
)
public class Movimiento  implements java.io.Serializable {


     private int idmovimiento;
     private Concepto concepto;
     private Departamento departamento;
     private Usuario usuario;
     private Date fecha;
     private Integer entrada;
     private Integer salida;

    public Movimiento() {
    }

	
    public Movimiento(int idmovimiento, Concepto concepto, Departamento departamento, Usuario usuario) {
        this.idmovimiento = idmovimiento;
        this.concepto = concepto;
        this.departamento = departamento;
        this.usuario = usuario;
    }
    public Movimiento(int idmovimiento, Concepto concepto, Departamento departamento, Usuario usuario, Date fecha, Integer entrada, Integer salida) {
       this.idmovimiento = idmovimiento;
       this.concepto = concepto;
       this.departamento = departamento;
       this.usuario = usuario;
       this.fecha = fecha;
       this.entrada = entrada;
       this.salida = salida;
    }
   
     @Id 

    
    @Column(name="idmovimiento", unique=true, nullable=false)
    public int getIdmovimiento() {
        return this.idmovimiento;
    }
    
    public void setIdmovimiento(int idmovimiento) {
        this.idmovimiento = idmovimiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idconcepto", nullable=false)
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddepartamento", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="entrada")
    public Integer getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Integer entrada) {
        this.entrada = entrada;
    }

    
    @Column(name="salida")
    public Integer getSalida() {
        return this.salida;
    }
    
    public void setSalida(Integer salida) {
        this.salida = salida;
    }




}


