package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table(name="movimiento"
    ,catalog="urcipy"
)
public class Movimiento  {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idmovimiento", unique=true, nullable=false)
     private int idmovimiento;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="concepto_idconcepto", nullable=false)
    private Concepto concepto;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="departamento_iddepartamento", nullable=false)
     private Departamento departamento;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
     private Usuario usuario;
     private Date fecha;
     private Integer entrada;
     private Integer salida;

    public Movimiento() {
    }

	
    public Movimiento( Concepto concepto, Departamento departamento, Usuario usuario) {

        this.concepto = concepto;
        this.departamento = departamento;
        this.usuario = usuario;
    }
    public Movimiento(Concepto concepto, Departamento departamento, Usuario usuario, Date fecha, Integer entrada, Integer salida) {

       this.concepto = concepto;
       this.departamento = departamento;
       this.usuario = usuario;
       this.fecha = fecha;
       this.entrada = entrada;
       this.salida = salida;
    }
   

    public int getIdmovimiento() {
        return this.idmovimiento;
    }
    
    public void setIdmovimiento(int idmovimiento) {
        this.idmovimiento = idmovimiento;
    }

    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }


    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }


    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="entrada")
    public Integer getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Integer entrada) {
        this.entrada = entrada;
    }

    
    @Column(name="salida")
    public Integer getSalida() {
        return this.salida;
    }
    
    public void setSalida(Integer salida) {
        this.salida = salida;
    }




}


