package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,catalog="urcipy"
)
public class Pais  {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idpais", unique=true, nullable=false)
     private Integer idpais;
     private String nompais;
     private String nacionalidad;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    @JsonIgnore
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Pais() {
    }

    public Pais(String nompais, String nacionalidad, Set<Ciudad> ciudads) {
       this.nompais = nompais;
       this.nacionalidad = nacionalidad;
       this.ciudads = ciudads;
    }
   

    public Integer getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(Integer idpais) {
        this.idpais = idpais;
    }

    
    @Column(name="nompais", length=20)
    public String getNompais() {
        return this.nompais;
    }
    
    public void setNompais(String nompais) {
        this.nompais = nompais;
    }

    
    @Column(name="nacionalidad", length=30)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }


    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


