package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="promocion"
    ,catalog="urcipy"
)
public class Promocion  implements java.io.Serializable {


     private Integer idpromocion;
     private Regional regional;
     private String comentario;
     private String ruta;
     private String titulo;

    public Promocion() {
    }

	
    public Promocion(Regional regional) {
        this.regional = regional;
    }
    public Promocion(Regional regional, String comentario, String ruta, String titulo) {
       this.regional = regional;
       this.comentario = comentario;
       this.ruta = ruta;
       this.titulo = titulo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpromocion", unique=true, nullable=false)
    public Integer getIdpromocion() {
        return this.idpromocion;
    }
    
    public void setIdpromocion(Integer idpromocion) {
        this.idpromocion = idpromocion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="regional_idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

    
    @Column(name="comentario", length=250)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="ruta", length=45)
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    
    @Column(name="titulo", length=45)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }




}


