package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Resultimio generated by hbm2java
 */
@Entity
@Table(name="resultimio"
    ,catalog="urcipy"
)
public class Resultimio  {


     private Integer idresultimio;
     private Evento evento;
     private Integer nro;
     private String categoria;
     private Integer poscategoria;
     private String nomparticipante;
     private Integer dorsal;
     private String ci;
     private Integer distancia;
     private Date tiempo;
     private String club;
     private Byte proceso;
     private Integer id;
    private Integer puntaje;
    private Integer completo;
    private String tiempos;
    private Integer puntua;
    private Integer puntajeaux;
    private Integer puntajeclub;
    private Integer idevento;

    public Resultimio() {
    }

	
    public Resultimio(Evento evento) {
        this.evento = evento;
    }
    public Resultimio(Evento evento, Integer nro, String categoria, Integer poscategoria, String nomparticipante, Integer dorsal, String ci, Integer distancia, Date tiempo, String club, Byte proceso, Integer id, Integer puntaje, Integer completo, String tiempos, Integer puntua, Integer puntajeaux, Integer puntajeclub, Integer idevento) {
       this.evento = evento;
       this.nro = nro;
       this.categoria = categoria;
       this.poscategoria = poscategoria;
       this.nomparticipante = nomparticipante;
       this.dorsal = dorsal;
       this.ci = ci;
       this.distancia = distancia;
       this.tiempo = tiempo;
       this.club = club;
       this.proceso = proceso;
       this.id=id;
       this.puntaje=puntaje;
       this.completo=completo;
       this.tiempos = tiempos;
       this.puntua=puntua;
       this.puntajeaux=puntajeaux;
        this.puntajeclub = puntajeclub;
        this.idevento = idevento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idresultimio", unique=true, nullable=false)
    public Integer getIdresultimio() {
        return this.idresultimio;
    }
    
    public void setIdresultimio(Integer idresultimio) {
        this.idresultimio = idresultimio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_idevento", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    
    @Column(name="nro")
    public Integer getNro() {
        return this.nro;
    }
    
    public void setNro(Integer nro) {
        this.nro = nro;
    }

    
    @Column(name="categoria", length=60)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="poscategoria")
    public Integer getPoscategoria() {
        return this.poscategoria;
    }
    
    public void setPoscategoria(Integer poscategoria) {
        this.poscategoria = poscategoria;
    }

    
    @Column(name="nomparticipante", length=90)
    public String getNomparticipante() {
        return this.nomparticipante;
    }
    
    public void setNomparticipante(String nomparticipante) {
        this.nomparticipante = nomparticipante;
    }

    
    @Column(name="dorsal")
    public Integer getDorsal() {
        return this.dorsal;
    }
    
    public void setDorsal(Integer dorsal) {
        this.dorsal = dorsal;
    }

    
    @Column(name="ci", length=20)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="distancia")
    public Integer getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(Integer distancia) {
        this.distancia = distancia;
    }


    @Temporal(TemporalType.TIME)
    @Column(name="tiempo", length=8)
    public Date getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(Date tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="club", length=60)
    public String getClub() {
        return this.club;
    }
    
    public void setClub(String club) {
        this.club = club;
    }

    
    @Column(name="proceso")
    public Byte getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Byte proceso) {
        this.proceso = proceso;
    }
    @Column(name="id")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    @Column(name = "puntaje")
    public Integer getPuntaje() {
        return puntaje;
    }

    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }

    @Column(name = "completo")
    public Integer getCompleto() {
        return completo;
    }

    public void setCompleto(Integer completo) {
        this.completo = completo;
    }

    @Column(name="tiempos", length=12)
    public String getTiempos() {
        return tiempos;
    }

    public void setTiempos(String tiempos) {
        this.tiempos = tiempos;
    }

    @Column(name = "puntua")
    public Integer getPuntua() {
        return puntua;
    }

    public void setPuntua(Integer puntua) {
        this.puntua = puntua;
    }
    @Column(name = "puntajeaux")
    public Integer getPuntajeaux() {
        return puntajeaux;
    }

    public void setPuntajeaux(Integer puntajeaux) {
        this.puntajeaux = puntajeaux;
    }
    @Column(name = "puntajeclub")
    public Integer getPuntajeclub() {
        return puntajeclub;
    }

    public void setPuntajeclub(Integer puntajeclub) {
        this.puntajeclub = puntajeclub;
    }




    @Override
    public String toString() {
        return "Resultimio{" +
                "nomparticipante='" + nomparticipante + '\'' +
                ", ci='" + ci + '\'' +
                ", club='" + club + '\'' +
                ", categoria='" + categoria + '\'' +
                ", poscategoria=" + poscategoria +
                ", tiempo=" + tiempo +
                '}';
    }

    public Integer getIdevento() {
        return idevento;
    }

    public void setIdevento(Integer idevento) {
        this.idevento = idevento;
    }
}


