package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resultimio generated by hbm2java
 */
@Entity
@Table(name="resultimio"
    ,catalog="urcipy"
)
public class Resultimio  implements java.io.Serializable {


     private Integer idresultimio;
     private Evento evento;
     private Integer nro;
     private String categoria;
     private Integer poscategoria;
     private String nomparticipante;
     private Integer dorsal;
     private String ci;
     private Integer distancia;
     private String tiempo;
     private String club;
     private Byte proceso;

    public Resultimio() {
    }

	
    public Resultimio(Evento evento) {
        this.evento = evento;
    }
    public Resultimio(Evento evento, Integer nro, String categoria, Integer poscategoria, String nomparticipante, Integer dorsal, String ci, Integer distancia, String tiempo, String club, Byte proceso) {
       this.evento = evento;
       this.nro = nro;
       this.categoria = categoria;
       this.poscategoria = poscategoria;
       this.nomparticipante = nomparticipante;
       this.dorsal = dorsal;
       this.ci = ci;
       this.distancia = distancia;
       this.tiempo = tiempo;
       this.club = club;
       this.proceso = proceso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idresultimio", unique=true, nullable=false)
    public Integer getIdresultimio() {
        return this.idresultimio;
    }
    
    public void setIdresultimio(Integer idresultimio) {
        this.idresultimio = idresultimio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_idevento", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    
    @Column(name="nro")
    public Integer getNro() {
        return this.nro;
    }
    
    public void setNro(Integer nro) {
        this.nro = nro;
    }

    
    @Column(name="categoria", length=60)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="poscategoria")
    public Integer getPoscategoria() {
        return this.poscategoria;
    }
    
    public void setPoscategoria(Integer poscategoria) {
        this.poscategoria = poscategoria;
    }

    
    @Column(name="nomparticipante", length=90)
    public String getNomparticipante() {
        return this.nomparticipante;
    }
    
    public void setNomparticipante(String nomparticipante) {
        this.nomparticipante = nomparticipante;
    }

    
    @Column(name="dorsal")
    public Integer getDorsal() {
        return this.dorsal;
    }
    
    public void setDorsal(Integer dorsal) {
        this.dorsal = dorsal;
    }

    
    @Column(name="ci", length=20)
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }

    
    @Column(name="distancia")
    public Integer getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(Integer distancia) {
        this.distancia = distancia;
    }

    
    @Column(name="tiempo", length=30)
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

    
    @Column(name="club", length=60)
    public String getClub() {
        return this.club;
    }
    
    public void setClub(String club) {
        this.club = club;
    }

    
    @Column(name="proceso")
    public Byte getProceso() {
        return this.proceso;
    }
    
    public void setProceso(Byte proceso) {
        this.proceso = proceso;
    }




}


