package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="urcipy"
)
public class Rol implements Serializable {


     private int idroles;
     private String nombre;

    private Set<UsuarioRol> usuarioRoles = new HashSet<>();

    public Rol() {
    }

	
    public Rol(int idroles) {
        this.idroles = idroles;
    }
    public Rol(int idroles, String nombre, Set<UsuarioRol> usuarioRoles) {
       this.idroles = idroles;
       this.nombre = nombre;
       this.usuarioRoles = usuarioRoles;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idroles", unique=true, nullable=false)
    public int getIdroles() {
        return idroles;
    }

    public void setIdroles(int idroles) {
        this.idroles = idroles;
    }


    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY,mappedBy = "rol")
    public Set<UsuarioRol> getUsuarioRoles() {
        return usuarioRoles;
    }

    public void setUsuarioRoles(Set<UsuarioRol> usuarioRoles) {
        this.usuarioRoles = usuarioRoles;
    }
}


