package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="urcipy"
)
public class Rol  implements java.io.Serializable {


     private int idrol;
     private String nombre;
     private Set<UsuarioRol> usuarioRols = new HashSet<>(0);

    public Rol() {
    }

	
    public Rol(int idrol) {
        this.idrol = idrol;
    }
    public Rol(int idrol, String nombre, Set<UsuarioRol> usuarioRols) {
       this.idrol = idrol;
       this.nombre = nombre;
       this.usuarioRols = usuarioRols;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idrol", unique=true, nullable=false)
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


