package com.sistema.urcipy.entidades;
// Generated 09/02/2023 11:28:52 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * Sugerencia generated by hbm2java
 */
@Entity
@Table(name="sugerencia"
    ,catalog="urcipy"
)
public class Sugerencia {


     private int idsugerencia;
     private Evento evento;
     private String nomsugerencia;
     private String comentario;

    public Sugerencia() {
    }

	
    public Sugerencia(Evento evento) {

        this.evento = evento;
    }
    public Sugerencia( Evento evento, String nomsugerencia, String comentario) {

       this.evento = evento;
       this.nomsugerencia = nomsugerencia;
       this.comentario = comentario;
    }
   
     @Id @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="idsugerencia", unique=true, nullable=false)
    public int getIdsugerencia() {
        return this.idsugerencia;
    }
    
    public void setIdsugerencia(int idsugerencia) {
        this.idsugerencia = idsugerencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_idevento", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    
    @Column(name="nomsugerencia", length=45)
    public String getNomsugerencia() {
        return this.nomsugerencia;
    }
    
    public void setNomsugerencia(String nomsugerencia) {
        this.nomsugerencia = nomsugerencia;
    }

    
    @Column(name="comentario", length=100)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


