package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Trayecto generated by hbm2java
 */
@Entity
@Table(name="trayecto"
    ,catalog="urcipy"
)
public class Trayecto implements Serializable {


     private int idtrayecto;
     private String nomtrayecto;
     
     private int km;


    private Set<Categoria> categorias = new HashSet<Categoria>(0);

    public Trayecto() {
    }

    public Trayecto( String nomtrayecto,int km, Set<Categoria> categorias) {
       this.nomtrayecto = nomtrayecto;
       this.km=km;
       this.categorias = categorias;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idtrayecto", unique=true, nullable=false)
    public int getIdtrayecto() {
        return idtrayecto;
    }

    public void setIdtrayecto(int idtrayecto) {
        this.idtrayecto = idtrayecto;
    }


    
    @Column(name="nomtrayecto", length=45)
    public String getNomtrayecto() {
        return this.nomtrayecto;
    }
    
    public void setNomtrayecto(String nomtrayecto) {
        this.nomtrayecto = nomtrayecto;
    }

    @Column(name="km")
    public int getKm() {
        return km;
    }

    public void setKm(int km) {
        this.km = km;
    }

    @OneToMany(fetch = FetchType.LAZY,mappedBy = "trayecto")
    @JsonIgnore
    public Set<Categoria> getCategorias() {
        return this.categorias;
    }

    public void setCategorias(Set<Categoria> categorias) {
        this.categorias = categorias;
    }
}


