package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="urcipy"
)
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String apellido;
     private String telefono;
     private String perfil;
     private String email;
     private String username;
     private String password;
     private Boolean enabled;
     private Set<Movimiento> movimientos = new HashSet<>(0);
     private Set<Corredor> corredors = new HashSet<>(0);
     private Set<UsuarioRol> usuarioRols = new HashSet<>(0);

    public Usuario() {
    }

    public Usuario(String nombre, String apellido, String telefono, String perfil, String email, String username, String password, Boolean enabled, Set<Movimiento> movimientos, Set<Corredor> corredors, Set<UsuarioRol> usuarioRols) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.perfil = perfil;
       this.email = email;
       this.username = username;
       this.password = password;
       this.enabled = enabled;
       this.movimientos = movimientos;
       this.corredors = corredors;
       this.usuarioRols = usuarioRols;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario", unique=true, nullable=false)
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="perfil")
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="username", length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="enabled")
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Corredor> getCorredors() {
        return this.corredors;
    }
    
    public void setCorredors(Set<Corredor> corredors) {
        this.corredors = corredors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


