package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name="usuario_rol"
    ,catalog="urcipy"
)
public class UsuarioRol  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idusuario_rol", unique=true, nullable=false)
     private int idusuarioRol;
    @ManyToOne(fetch=FetchType.EAGER)
    private Rol rol;
    @ManyToOne(fetch=FetchType.EAGER)
     private Usuario usuario;



    public int getIdusuarioRol() {
        return this.idusuarioRol;
    }
    
    public void setIdusuarioRol(int idusuarioRol) {
        this.idusuarioRol = idusuarioRol;
    }


    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }


    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
