package com.sistema.urcipy.entidades;
// Generated 03/02/2023 12:59:13 AM by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name="usuario_rol"
    ,catalog="urcipy"
)
public class UsuarioRol  implements java.io.Serializable {


     private int idusuarioRol;
     private Regional regional;
     private Rol rol;
     private Usuario usuario;

    public UsuarioRol() {
    }

    public UsuarioRol(int idusuarioRol, Regional regional, Rol rol, Usuario usuario) {
       this.idusuarioRol = idusuarioRol;
       this.regional = regional;
       this.rol = rol;
       this.usuario = usuario;
    }

    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario_rol", unique=true, nullable=false)
    public int getIdusuarioRol() {
        return this.idusuarioRol;
    }
    
    public void setIdusuarioRol(int idusuarioRol) {
        this.idusuarioRol = idusuarioRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregional", nullable=false)
    public Regional getRegional() {
        return this.regional;
    }
    
    public void setRegional(Regional regional) {
        this.regional = regional;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idrol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


